-- AlterTable
ALTER TABLE `client` ADD COLUMN `accountNo` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `address_ru` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `address_tm` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `bankIdCode` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `bankName_ru` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `bankName_tm` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `clientType` ENUM('BUYER', 'SELLER') NOT NULL DEFAULT 'BUYER',
    ADD COLUMN `correspondentAccount` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `currentAccount` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `directorName_ru` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `directorName_tm` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `individualIdNumber` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `swift` VARCHAR(191) NOT NULL DEFAULT '';
